swagger: "2.0"
info:
  title: Gateway
  version: 0.0.1
schemes:
- http
consumes:
- application/json
produces:
- application/json

basePath: /api

paths:
  /auth/register:
    $ref: "./gateway-auth.yaml#/api/register"

  /auth/login:
    $ref: "./gateway-auth.yaml#/api/login"

  /auth/logout:
    $ref: "./gateway-auth.yaml#/api/logout"


