[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.1.0"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"
