// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/user/user_repository.go

// Package user is a generated GoMock package.
package user

import (
	exception "github.com/a-trium/domain-driven-design/implementation-1ambda/service-gateway/internal/exception"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddUser mocks base method
func (m *MockRepository) AddUser(user *User) (*User, exception.Exception) {
	ret := m.ctrl.Call(m, "AddUser", user)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(exception.Exception)
	return ret0, ret1
}

// AddUser indicates an expected call of AddUser
func (mr *MockRepositoryMockRecorder) AddUser(user interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockRepository)(nil).AddUser), user)
}

// DeleteUser mocks base method
func (m *MockRepository) DeleteUser(id uint) (bool, exception.Exception) {
	ret := m.ctrl.Call(m, "DeleteUser", id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(exception.Exception)
	return ret0, ret1
}

// DeleteUser indicates an expected call of DeleteUser
func (mr *MockRepositoryMockRecorder) DeleteUser(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockRepository)(nil).DeleteUser), id)
}

// FindUserById mocks base method
func (m *MockRepository) FindUserById(id uint) (*User, exception.Exception) {
	ret := m.ctrl.Call(m, "FindUserById", id)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(exception.Exception)
	return ret0, ret1
}

// FindUserById indicates an expected call of FindUserById
func (mr *MockRepositoryMockRecorder) FindUserById(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserById", reflect.TypeOf((*MockRepository)(nil).FindUserById), id)
}

// FineAllUsers mocks base method
func (m *MockRepository) FineAllUsers() (*[]User, exception.Exception) {
	ret := m.ctrl.Call(m, "FineAllUsers")
	ret0, _ := ret[0].(*[]User)
	ret1, _ := ret[1].(exception.Exception)
	return ret0, ret1
}

// FineAllUsers indicates an expected call of FineAllUsers
func (mr *MockRepositoryMockRecorder) FineAllUsers() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FineAllUsers", reflect.TypeOf((*MockRepository)(nil).FineAllUsers))
}
